on:
  workflow_call:
    inputs:
      repository: 
        description: 'Repository to release'
        required: true
        type: string
      registry:
        description: 'Registry to push the image'
        required: false
        type: string
        default: 'ghcr.io'

name: Release
jobs:
  convert:
    runs-on: ubuntu-latest
    outputs:
      repository: ${{ steps.string.outputs.lowercase }}
    steps:
      - id: string
        uses: vishalmamidi/lowercase-action@v1
        with:
          string: ${{inputs.repository}}
      - name: echo lowercase
        run: echo "${{ steps.string.outputs.lowercase }}" >> $GITHUB_OUTPUT

  Release:
    runs-on: ubuntu-latest
    needs: convert
    container: 
        image: ${{ inputs.registry }}/${{ needs.convert.outputs.repository }}
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      pull-requests: write
      issues: write
      discussions: write
      packages: write

    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: run release
          run: "semantic-release --dry-run"
