on:
  workflow_call:
    inputs:
      repository: 
        description: 'Repository to release'
        required: true
        type: string
      registry:
        description: 'Registry to push the image'
        required: false
        type: string
        default: 'ghcr.io'

name: Release
jobs:
  convert:
    runs-on: ubuntu-latest
    outputs:
      repository: ${{ steps.string.outputs.lowercase }}
    steps:
      - id: string
        uses: vishalmamidi/lowercase-action@v1
        with:
          string: ${{inputs.repository}}
      - name: echo lowercase
        run: echo "repository=${{ steps.string.outputs.lowercase }}" >> "$GITHUB_OUTPUT"
      - name: Set outputs
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

  Release:
    runs-on: ubuntu-latest
    needs: convert
    env:
      REGISTRY: ${{ inputs.registry }}
      IMAGE_NAME: ${{ needs.convert.outputs.repository }}
    container: 
        image: ${{ inputs.registry }}/${{ needs.convert.outputs.repository }}:sha-${{ needs.convert.outputs.sha_short }}
        credentials:
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      contents: write
      pull-requests: write
      issues: write
      discussions: write
      packages: write

    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0
        - name: run release
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          run: "semantic-release"
